services:
  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    environment:
      APP_FULL_BASE_URL: https://passbolt.docchula.com
    # Load environment variables from Portainer stack configuration
    env_file:
      - stack.env
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command: "/docker-entrypoint.sh"
    labels:
      # Traefik configuration discovery
      # https://doc.traefik.io/traefik/providers/docker/#routing-configuration-with-labels
      - "traefik.enable=true"
      - "traefik.http.middlewares.passbolt-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.passbolt-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.passbolt-http.middlewares=passbolt-redirect"
      - "traefik.http.routers.passbolt-http.rule=Host(`passbolt.docchula.com`)"
      - "traefik.http.routers.passbolt-http.entrypoints=web"
      - "traefik.http.routers.passbolt-https.rule=Host(`passbolt.docchula.com`)"
      - "traefik.http.routers.passbolt-https.entrypoints=websecure"
      - "traefik.http.routers.passbolt-https.tls.certresolver=leresolver"
      - "traefik.http.services.passbolt-https.loadbalancer.server.port=80"

volumes:
  gpg_volume:
  jwt_volume:
